
-- create view that shows quantity sold and revenue generated by each employee
CREATE VIEW quantity_revenue_view AS
SELECT 
    SUM(quantity) AS quantity_sold, SUM(quantity * unitPrice * (1.0 - discount)) AS revenue_generated
FROM OrderDetails
GROUP BY employeeID;