
-- create view that shows quantity sold and revenue generated by each employee
CREATE VIEW IF NOT EXISTS quantity_revenue_view AS
SELECT 
    employeeID, SUM(quantity) AS quantity_sold, SUM(quantity * unitPrice * (1.0 - discount)) AS revenue_generated
FROM OrderDetails
INNER JOIN Orders ON Orders.orderID=OrderDetails.orderID
GROUP BY employeeID;

SELECT * FROM quantity_revenue_view 
INTO OUTFILE '/var/lib/mysql-files/dumps/db_view.csv'
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n';